### ISSUE TITLE
Error on step 1

### ISSUE THREAD

**Issue by KenKenhehe** [ignfab/building-roof-pipeline#5]
So I cloned the repo and did the dependency install, everything good so far.
Then when I try step 1:
```
 cd building-roof-pipeline/
   bash patch_scripts.sh
``` 

I get these error? not sure how to fix, can you help?
```
patch_scripts.sh: line 2: $'\r': command not found
patch_scripts.sh: line 5: $'\r': command not found
: No such file or directorypplibs_version.cfg
patch_scripts.sh: line 8: $'\r': command not found
```

**Comment by indyteo** [comment]
Hello,
Thank you for your interest in this project!

It seems that the encoding of your file is CRLF (Windows-style line endings) instead of just LF (Unix-style line endings). You should convert the file by running:
```
sed -i 's/\r$//' patch_scripts.sh
```

You can run this command on any other file where you encounter the same kind of issue (`$'\r': command not found`) by replacing the filename at the end of the command.

Let me know if you encounter further issue with this project, I'd be happy to try my best to solve them! By the way, may I ask you what kind of work are you doing with this project? Always nice to see people that are interested by our work 😊

**Comment by KenKenhehe** [comment]
Thanks for getting back!

Yes I applied the fix and it seem to be working

But I have encountered another issue when I run :
```
bash dl_and_build_cpplibs.sh -dc  
```

one of the library is not able to download? 

```
Cannot download http://glaros.dtc.umn.edu/gkhome/fetch/sw/hmetis/hmetis-1.5-linux.tar.gz
```

**Comment by indyteo** [comment]
Well, it's not the first time the website of this library is down... I'll check next week if I have a local copy of the archive on my computed (maybe @esgn has one as well?) and I'll host it somewhere else because it's a bit annoying to deals with their outages.

In the mean time, I suggest you to comment the lines 207 to 209 as well as the line 288 of the build script to avoid the problem. We should be able to compile without, however I'm unsure about what will and won't work, but @esgn may be able to give you a bit more information about this.

**Comment by indyteo** [comment]
Unfortunately, I don't have a local copy of this lib on my compute, however, it seems [this GitHub repository](https://github.com/parastuffs/metis_unicorn) contains the source code of this lib. Thus, you can download it with this link:
https://github.com/parastuffs/metis_unicorn/raw/master/hmetis-1.5-linux.tar.gz

Replace the broken link in your `dl_and_build_cpplibs.sh` script (line 207) and it should do the work!
